### ISSUE TITLE
Please make a new release?

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-tar_scm#226] opened 2018-03-13 12:36 UTC
I'm trying to package this source service for Fedora, but it seems like it hasn't had a release in two years.

Can a new release be made soon?

**Comment by aspiers** [comment] 2018-03-16 00:11
Thanks for the nudge.  This is a duplicate of #91 so let's close this and track it there.

**Closed by aspiers** 2018-03-16 00:11 UTC
