### ISSUE TITLE
Add tag signature verification

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/obs-service-tar_scm#220] opened 2018-02-06 09:49 UTC
Please add the possibility to verify signed tags!

**Comment by aspiers** [comment] 2018-02-06 14:27
Sounds like a cool idea; please could you give more details about how you would expect this to work? e.g. what would a sample `_service` file look like?

**Comment by aspiers** [comment] 2018-02-06 14:28
Hrm, actually I think this is a duplicate of #127, so let's continue the discussion there.  (If you disagree we can easily reopen this.)

**Closed by aspiers** 2018-02-06 14:28 UTC
Labels: enhancement, need info
