### ISSUE TITLE
need way to transform things like @PARENT_TAG@

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-service-tar_scm#111] opened 2016-07-06 12:26 UTC
some projects have tags which result in things like from git describe --tags:

```
v8.4.0.rc1-9121-gcfd5870
release-2.1.0-1186-g507ed2d
```

it would be nice to be able to transform the result of versionformat.

```
<services>
  <service name="obs_scm">
    <param name="url">https://gitlab.com/gitlab-org/gitlab-ce.git</param>
    <param name="versionformat">@PARENT_TAG@~git@TAG_OFFSET@.%h</param>
    <param name="revision">master</param>
    <param name="scm">git</param>
    <param name="changesgenerate">enable</param>
  </service>
[snip]
</services>
```

could be handled with something like

```
    <param name="versionformat" match='v(.*)' replace='$1'>@PARENT_TAG@~git@TAG_OFFSET@.%h</param>
```

```
    <param name="versionformat" match='release-(.*)' replace='$1'>@PARENT_TAG@~git@TAG_OFFSET@.%h</param>
```

i know executing user provided regexp can be dangerous, so i am open to better solutions.

**Comment by aspiers** [comment] 2016-07-27 14:18
Thanks - you're right, and your `match` / `replace` idea looks quite nice.  However please note that this is pretty much a duplicate of #92, and is also quite related to #60 and #55.  I'm trying to figure out a clean, general solution which makes everyone happy.

I could just merge #114 which I *think* would probably address your particular needs, since you only need to strip prefixes.  But other people need to do other regexp-based munging, and I'm not keen on implementing two layers of munging if one can do the job for everyone.  Help welcome on the design side (I expect the actual coding to be simple).  Maybe it's worth creating a wiki page which captures everyone's use cases and proposes a best-of-breed solution.

**Comment by aspiers** [comment] 2016-07-27 14:20
Note also [the security concerns](https://github.com/openSUSE/obs-service-tar_scm/issues/60#issuecomment-227417336) in #60 which would be introduced by trying to make this too flexible.

**Comment by aspiers** [comment] 2016-07-27 14:27
I've labelled all issues and PRs relating to this: https://github.com/openSUSE/obs-service-tar_scm/labels/version%20calculation

**Comment by bluca** [comment] 2017-04-03 15:55
Looks like a solution was deployed on build.opensuse.org (although cannot see it in this repo) as the following parameters are now available:

```
  <parameter name="versionrewrite-pattern">
    <description>
      Regex used to rewrite the version which is applied post versionformat. For
      example, to remove a tag prefix of "v" the regex "v(.*)" could be used.
      See the versionrewrite-replacement parameter.
    </description>
  </parameter>
  <parameter name="versionrewrite-replacement">
    <description>
      Replacement applied to rewrite pattern. Typically backreferences are
      useful and as such defaults to \1.
    </description>
  </parameter>
```

**Comment by ddiss** [comment] 2017-04-13 15:12
So can this new functionality be depended upon, given that it's not carried in the master branch, but has been deployed on the OBS from a user branch?

**Comment by aspiers** [comment] 2017-04-13 16:23
@ddiss This is now in `master` :-) https://github.com/openSUSE/obs-service-tar_scm/pull/132/commits/960d0cebad3bbf86102991eb38c542bbf5a16df4 from #132. So we can close this at last!

**Comment by aspiers** [comment] 2017-04-13 16:24
(and @M0ses is working on repointing OBS back to `master`)

**Closed by aspiers** 2017-04-13 16:23 UTC
Labels: enhancement, help wanted, version calculation
