### ISSUE TITLE
ANSI escape colors do not work in OBS

### ISSUE THREAD

**Issue by kaltsi** [openSUSE/obs-service-tar_scm#81] opened 2015-09-18 09:28 UTC
Some of the error messages that tar_sm prints out use ANSI escaping to colorize text:

\e[0;31mThe git repository has no tags, thus @PARENT_TAG@ can not be expanded\e[0m

Those ANSI escapes do not work when the error is shown in OBS and they are just printed out with the rest of the message. They will just make the error output look less readable.

**Comment by aspiers** [comment] 2015-09-18 10:21
Good point, thanks.  This can be easily fixed by only including colour if `os.isatty(sys.stdin.fileno())` is `True`.  Pull requests very welcome ;-)

On a related topic, I wonder if it's worth using [ansicolors](https://pypi.python.org/pypi/ansicolors/1.0.2).  Although since `tar_scm` is required in minimal build environments, so extra dependencies are probably a bad idea.

**Comment by kaltsi** [comment] 2015-09-18 10:40
I think colors are not that important in this case. None of the other sys.exit() cases in tar_scm colorize the output either. Instead of the colors I'd prefix the errors with prominent string like ERROR: or FAIL:

**Comment by aspiers** [comment] 2015-09-18 11:18
Prefixing with `ERROR:` or similar is a good idea, but colours are a useful visual aid, and this issue is trivial to fix, so we should keep them.

**Comment by aspiers** [comment] 2015-11-01 09:58
@kaltsi Please could you provide a URL to a build where this is reproduced?  Thanks.

**Comment by kaltsi** [comment] 2015-11-01 11:13
Looks like it behaves differently in build.opensuse.org and in my private obs and I can't provide links there, sorry.

The difference is that my private obs is not using lxc containers to run the services and I get the output from tar_scm directly. In build.opensuse.org you'll just get a nonspecific error like this:

https://build.opensuse.org/package/show/home:kaltsi/test-service-notags

**Comment by aspiers** [comment] 2015-11-06 21:28
Actually, this issue was nothing to do with OBS, it was a simple bug in the code which has since been fixed by #83.

**Closed by aspiers** 2015-11-06 21:28 UTC
