### ISSUE TITLE
Problems extracting github sources

### ISSUE THREAD

**Issue by Area51Kacz** [openSUSE/obs-service-tar_scm#409] opened 2021-05-14 02:30 UTC
**OBS target - Arch linux**
Source origin: GIT
I clone git repos (via obs webclient)     - but i get a weird error 
`nothing provides obs-service-tar, nothing provides obs-service-recompress, nothing provides obs-service-set_version`

my package  https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/brave

**Comment by M0ses** [comment] 2021-06-07 12:57
This is not a bug of obs-service-tar_scm. Its an packaging issue. For those discussions its better to ask in #openbuild-service on freenode or the buildservice mailing list: buildservice@lists.opensuse.org

Anyway, back to your issue:

According to the Arch Linux package search 
(https://archlinux.org/packages/?sort=&q=obs-service-tar_scm&maintainer=&flagged=)
obs-service-tar_scm is not part of Arch Linux. 
If you want to use it anyway, you need a project where it is built for Arch Linux. I would recommend

 https://build.opensuse.org/package/live_build_log/openSUSE:Tools/obs-service-tar_scm/Arch/x86_64

even its an older version (0.10.14 vs. 0.10.25). 
This is our devel project where you can find the newest versions.

And an additional hint - chromium source are quite huge - ATM you may run into a service timeout. But you can disable the services and run them locally on your devel machine and commit to OBS until we have a fix for this.

**Closed by M0ses** 2021-06-07 12:57 UTC
